[install.security]
# scanner = "@bun-security-scanner/npm"

[install]
# Only install package versions published at least 7 days ago
# minimumReleaseAge = 604800
# Temporarily removed minimumReleaseAge restriction for a security patch; revert on or after 22.01.2026
minimumReleaseAge = 0