[package]
name = "temp"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []

[dependencies]
arcstr = { version = "1.2.0" }
paste = { version = "1.0.12" }
derive_more = { version = "0.99.17", features = ["add", "not", "from"] }
dbsp = { path = "../../crates/dbsp", features = ["backend-mode"] }
dbsp_adapters = { path = "../../crates/adapters", default-features = false }
feldera-types = { path = "../../crates/feldera-types" }
feldera-sqllib = { path = "../../crates/sqllib" }
serde = { version = "1.0", features = ["derive"] }
compare = { version = "0.1.0" }
size-of = { version = "0.1.5", package = "feldera-size-of" }
serde_json = { version = "1.0.127", features = ["arbitrary_precision"] }
rkyv = { version = "0.7.45", default-features = false, features = ["std", "size_64"] }
erased-serde = "0.3.31"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
hashing = { path = "../lib/hashing" }
readers = { path = "../lib/readers" }
uuid = { version = "1.6.1" }
# Used only in some unit tests
metrics = { version = "0.23.0" }
metrics-util = { version = "0.17.0" }
sltsqlvalue = { path = "../lib/sltsqlvalue" }

[lib]
path = "src/lib.rs"
doctest = false

# Incremental builds sometimes crash the Rust compiler
#[profile.test]
#incremental = false
