[package]
name = "temp"
version = "0.1.0"
edition = "2021"

[features]
jit = [ "dep:dataflow-jit" ]

[dependencies]
paste = { version = "1.0.12" }
derive_more = { version = "0.99.17", features = ["add", "not", "from"] }
dbsp = { path = "../../crates/dbsp", features = ["with-serde"], default-features = false }
dbsp_adapters = { path = "../../crates/adapters", default-features = false }
dataflow-jit = { path = "../../crates/dataflow-jit", optional = true }
tuple = { path = "../lib/tuple" }
sqllib = { path = "../lib/sqllib" }
sqlvalue = { path = "../lib/sqlvalue" }
serde = { version = "1.0", features = ["derive"] }
compare = { version = "0.1.0" }
size-of = { version = "0.1.1" }
geo = { version = "0.25.1" }
geo-types = { version = "0.7" }
serde_json = { version = "1.0.89" }
chrono = { version = "0.4.23" }
bincode = { version = "2.0.0-rc.2", features = ["serde"] }

[dev-dependencies]
hashing = { path = "../lib/hashing" }
readers = { path = "../lib/readers" }
sqlx = { version = "0.6", features = [ "runtime-async-std-native-tls", "sqlite", "any" ] }

[lib]
path = "src/lib.rs"
doctest = false

# Incremental builds sometimes crash the compiler
[profile.test]
incremental = false
# Without this in debug builds overflows cause panics
overflow-checks = false
