[package]
name = "temp"
version = "0.1.0"
edition = "2021"
publish = false

[features]

[dependencies]
paste = { version = "1.0.12" }
derive_more = { version = "0.99.17", features = ["add", "not", "from"] }
dbsp = { path = "../../crates/dbsp" }
dbsp_adapters = { path = "../../crates/adapters", default-features = false }
pipeline_types = { path = "../../crates/pipeline-types" }
sqllib = { path = "../lib/sqllib" }
json = { path = "../lib/json" }
sqlvalue = { path = "../lib/sqlvalue" }
serde = { version = "1.0", features = ["derive"] }
compare = { version = "0.1.0" }
size-of = { git = "https://github.com/gz/size-of.git", rev = "f8e6be7" }
geo = { version = "0.26.0" }
geo-types = { version = "0.7" }
rust_decimal = { git = "https://github.com/gz/rust-decimal.git", rev = "ea85fdf" }
serde_json = { version = "1.0.127" }
chrono = { version = "0.4.38" }
rkyv = { version = "0.7", default-features = false, features = ["std", "size_64"] }
num = { version = "0.4.1" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5.4", features = ["profiling", "unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
hashing = { path = "../lib/hashing" }
readers = { path = "../lib/readers" }
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "sqlite", "any"] }
uuid = { version = "1.6.1" }
# Used only in some unit tests
metrics = { version = "0.23.0" }
metrics-util = { version = "0.17.0" }

[lib]
path = "src/lib.rs"
doctest = false

# Incremental builds sometimes crash the Rust compiler
[profile.test]
incremental = false

[patch.crates-io]
rkyv = { git = "https://github.com/gz/rkyv.git", rev = "3d3fd86" }
rust_decimal = { git = "https://github.com/gz/rust-decimal.git", rev = "ea85fdf" }
size-of = { git = "https://github.com/gz/size-of.git", rev = "f8e6be7" }
