# Additional services needed to test/demo Debezium integration
name: feldera-debezium
services:
  # MySQL container with a toy database used in the Debezium
  # MySQL tutorial (based on MySQL 8.0).
  mysql:
    image: debezium/example-mysql:2.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e 'USE inventory;'"]
      interval: 5s
      timeout: 5s
      # MySQL can be _very_ slow to start.
      retries: 40

  # Feldera demo container that creates a Debezium MySQL connector to
  # sync the MySQL database with Feldera.
  debezium-demo:
    depends_on:
      pipeline-manager:
        condition: service_healthy
      connect:
        condition: service_healthy
      mysql:
        condition: service_healthy
    image: ghcr.io/feldera/demo-container:${FELDERA_VERSION:-0.17.0}
    environment:
      RUST_BACKTRACE: "1"
      REDPANDA_BROKERS: "redpanda:9092"
      RUST_LOG: "info"
      KAFKA_CONNECT_SERVER: "http://connect:8083"
    command:
      - bash
      - -c
      - "sleep 20 && cd demo/project_demo05-DebeziumMySQL/ && python3 run.py --api-url http://pipeline-manager:8080 --start"
