[package]
name = "tiktok-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
fake = { version = "2.10", features = ["derive", "chrono"] }
rand = "0.8.5"
rdkafka = "0.36.2"
serde = { version = "1.0.204", features = ["derive"] }
