[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "feldera"
description = "The feldera python client"
version = "0.0.1"
license = { text = "MIT" }
requires-python = ">3.10"
authors = [
    { "name" = "Abhinav", "email" = "abhinav@feldera.com" },
]
keywords = [
    "feldera",
    "python",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "pandas",
    "typing-extensions",
]
[project.urls]
Homepage = "https://www.feldera.com"
Documentation = "https://www.feldera.com/docs"
Repository = "https://github.com/feldera/feldera"
Issues = "https://github.com/feldera/feldera/issues"
Changelog = "https://github.com/feldera/feldera/blob/main/CHANGELOG.md"
